/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.traceability.deep;import cn.zhuatech.traceability.model.AuditLog;import cn.zhuatech.traceability.repository.AuditLogRepository;import jakarta.persistence.*;import jakarta.validation.constraints.*;import org.springframework.http.HttpStatus;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import org.springframework.web.server.ResponseStatusException;import java.time.*;import java.util.*;
/**
 * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
 */
@Service @Transactional(readOnly=true) public class DeepDomainService{private final EntityManager em;private final AuditLogRepository logs;/**
                                                                                                                                            * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                            */
public DeepDomainService(EntityManager e,AuditLogRepository l){em=e;logs=l;}/**
                                                                                                                                                                                                                        * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                        */
public Dashboard dashboard(String o){return new Dashboard(batches(o),events(o),recalls(o));}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 @Transactional public BatchView batch(BatchRequest r){if(r.expiryDate()!=null&&r.expiryDate().isBefore(r.productionDate()))throw bad("失效日期不能早于生产日期");var b=new ProductBatch(r.organizationCode(),r.batchNo(),r.materialCode(),r.batchType(),r.quantity(),r.productionDate(),r.expiryDate());em.persist(b);audit("TRACE_BATCH","建立批次",b.batchNo,b.materialCode);return view(b);}/**
                                                                                                                                                                                                                                                                                                                                                                                 * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                 */
@Transactional public InspectionView inspect(Long id,InspectionRequest r){var b=batch(id);if(!"QUARANTINE".equals(b.status))throw conflict("只有待检批次可以登记检验");var x=new BatchInspection(id,r.inspectionNo(),r.result(),r.conclusion(),r.inspector());em.persist(x);audit("TRACE_QUALITY","登记检验",x.inspectionNo,r.result());return view(x);}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         */
@Transactional public BatchView release(Long id){var b=batch(id);if(!"QUARANTINE".equals(b.status))throw conflict("当前批次不能放行");long passed=em.createQuery("select count(i) from BatchInspection i where i.batchId=:id and i.result='PASSED'",Long.class).setParameter("id",id).getSingleResult();if(passed==0)throw conflict("批次必须通过质量检验后才能放行");b.status="RELEASED";audit("TRACE_BATCH","质量放行",b.batchNo,"inspection passed");return view(b);}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 @Transactional public GenealogyView consume(GenealogyRequest r){var s=batch(r.sourceBatchId());var t=batch(r.targetBatchId());if(!s.organizationCode.equals(t.organizationCode))throw bad("来源与目标批次必须属于同一组织");if(s.id.equals(t.id))throw bad("来源与目标批次不能相同");if(!"RELEASED".equals(s.status))throw conflict("只有已放行批次可以投入生产");if(!"QUARANTINE".equals(t.status))throw conflict("目标产出批次必须处于待检状态");if(s.allocatedQuantity+r.consumedQuantity()>s.quantity)throw conflict("投入数量超过来源批次可用数量");s.allocatedQuantity+=r.consumedQuantity();var g=new BatchGenealogy(s.id,t.id,r.consumedQuantity(),r.processStep());em.persist(g);audit("TRACE_GENEALOGY","建立批次谱系",t.batchNo,s.batchNo+" -> "+t.batchNo);return view(g);}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 @Transactional public EventView event(Long id,EventRequest r){var b=batch(id);if("QUARANTINE".equals(b.status)&&!"PRODUCTION".equals(r.eventType()))throw conflict("待检批次不能进入仓储或销售事件");var e=new TraceEvent(r.eventId(),id,r.eventType(),r.location(),r.businessRef(),r.occurredAt());em.persist(e);audit("TRACE_EVENT","登记追溯事件",e.eventId,b.batchNo+"/"+r.eventType());return view(e);}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 @Transactional public RecallView recall(RecallRequest r){var b=batch(r.sourceBatchId());Set<Long> affected=new HashSet<>();affected.add(b.id);boolean changed=true;while(changed){int before=affected.size();var edges=em.createQuery("select g from BatchGenealogy g",BatchGenealogy.class).getResultList();for(var g:edges)if(affected.contains(g.sourceBatchId))affected.add(g.targetBatchId);changed=affected.size()>before;}var x=new RecallCase(r.recallNo(),b.id,r.level(),r.reason(),affected.size());em.persist(x);audit("TRACE_RECALL","启动召回",x.recallNo,"affected="+affected.size());return view(x);}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  */
@Transactional public RecallView notifyRecall(Long id){var r=recall(id);if(!"OPEN".equals(r.status))throw conflict("召回状态不可通知");r.status="NOTIFIED";r.notifiedAt=LocalDateTime.now();audit("TRACE_RECALL","通知召回",r.recallNo,"affected="+r.affectedBatchCount);return view(r);}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               */
@Transactional public RecallView closeRecall(Long id){var r=recall(id);if(!"NOTIFIED".equals(r.status))throw conflict("完成通知后才能关闭召回");r.status="CLOSED";audit("TRACE_RECALL","关闭召回",r.recallNo,r.reason);return view(r);}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 private List<BatchView>batches(String o){return em.createQuery("select b from ProductBatch b where b.organizationCode=:o order by b.createdAt desc",ProductBatch.class).setParameter("o",o).getResultList().stream().map(this::view).toList();}/**
                                                                                                                                                                                                                                                 * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                 */
private List<EventView>events(String o){return em.createQuery("select e from TraceEvent e where e.batchId in(select b.id from ProductBatch b where b.organizationCode=:o) order by e.occurredAt desc",TraceEvent.class).setParameter("o",o).getResultList().stream().map(this::view).toList();}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                */
private List<RecallView>recalls(String o){return em.createQuery("select r from RecallCase r where r.sourceBatchId in(select b.id from ProductBatch b where b.organizationCode=:o) order by r.openedAt desc",RecallCase.class).setParameter("o",o).getResultList().stream().map(this::view).toList();}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     */
private ProductBatch batch(Long id){var x=em.find(ProductBatch.class,id);if(x==null)throw missing("批次不存在");return x;}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          */
private RecallCase recall(Long id){var x=em.find(RecallCase.class,id);if(x==null)throw missing("召回单不存在");return x;}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             */
private void audit(String m,String a,String n,String d){logs.save(new AuditLog(m,a,n,"trace-domain",d));}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      */
private ResponseStatusException bad(String m){return new ResponseStatusException(HttpStatus.BAD_REQUEST,m);}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  */
private ResponseStatusException conflict(String m){return new ResponseStatusException(HttpStatus.CONFLICT,m);}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                */
private ResponseStatusException missing(String m){return new ResponseStatusException(HttpStatus.NOT_FOUND,m);}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 private BatchView view(ProductBatch b){return new BatchView(b.id,b.organizationCode,b.batchNo,b.materialCode,b.batchType,b.quantity,b.allocatedQuantity,b.status,b.productionDate,b.expiryDate,b.version);}/**
                                                                                                                                                                                                             * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                             */
private InspectionView view(BatchInspection i){return new InspectionView(i.id,i.batchId,i.inspectionNo,i.result,i.conclusion,i.inspector,i.inspectedAt);}/**
                                                                                                                                                                                                                                                                                                                                                                      * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                      */
private GenealogyView view(BatchGenealogy g){return new GenealogyView(g.id,g.sourceBatchId,g.targetBatchId,g.consumedQuantity,g.processStep);}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    */
private EventView view(TraceEvent e){return new EventView(e.id,e.eventId,e.batchId,e.eventType,e.location,e.businessRef,e.occurredAt);}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           */
private RecallView view(RecallCase r){return new RecallView(r.id,r.recallNo,r.sourceBatchId,r.level,r.reason,r.status,r.affectedBatchCount,r.openedAt,r.notifiedAt);}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 public record BatchRequest(@NotBlank String organizationCode,@NotBlank String batchNo,@NotBlank String materialCode,@NotBlank String batchType,@Positive double quantity,@NotNull LocalDate productionDate,LocalDate expiryDate){}/**
                                                                                                                                                                                                                                    * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                    */
public record InspectionRequest(@NotBlank String inspectionNo,@Pattern(regexp="PASSED|FAILED")String result,@NotBlank String conclusion,@NotBlank String inspector){}/**
                                                                                                                                                                                                                                                                                                                                                                                                         * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                         */
public record GenealogyRequest(@NotNull Long sourceBatchId,@NotNull Long targetBatchId,@Positive double consumedQuantity,@NotBlank String processStep){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 */
public record EventRequest(@NotBlank String eventId,@NotBlank String eventType,@NotBlank String location,@NotBlank String businessRef,@NotNull LocalDateTime occurredAt){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           */
public record RecallRequest(@NotBlank String recallNo,@NotNull Long sourceBatchId,@NotBlank String level,@NotBlank String reason){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              */
public record BatchView(Long id,String organizationCode,String batchNo,String materialCode,String batchType,double quantity,double allocatedQuantity,String status,LocalDate productionDate,LocalDate expiryDate,long version){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              */
public record InspectionView(Long id,Long batchId,String inspectionNo,String result,String conclusion,String inspector,LocalDateTime inspectedAt){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 */
public record GenealogyView(Long id,Long sourceBatchId,Long targetBatchId,double consumedQuantity,String processStep){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        */
public record EventView(Long id,String eventId,Long batchId,String eventType,String location,String businessRef,LocalDateTime occurredAt){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   */
public record RecallView(Long id,String recallNo,Long sourceBatchId,String level,String reason,String status,int affectedBatchCount,LocalDateTime openedAt,LocalDateTime notifiedAt){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         */
public record Dashboard(List<BatchView>batches,List<EventView>events,List<RecallView>recalls){}
}
