/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.traceability.deep;import jakarta.persistence.*;import java.time.*;
/**
 * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
 */
@Entity @Table(name="tr_batches",uniqueConstraints=@UniqueConstraint(columnNames={"organizationCode","batchNo"})) class ProductBatch{@Id @GeneratedValue(strategy=GenerationType.IDENTITY)Long id;@Version long version;@Column(nullable=false,length=40)String organizationCode;@Column(nullable=false,length=60)String batchNo;@Column(nullable=false,length=60)String materialCode;@Column(nullable=false,length=30)String batchType;double quantity;double allocatedQuantity;@Column(nullable=false,length=20)String status="QUARANTINE";LocalDate productionDate;LocalDate expiryDate;LocalDateTime createdAt;/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    */
protected ProductBatch(){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              */
ProductBatch(String o,String n,String m,String t,double q,LocalDate p,LocalDate e){organizationCode=o;batchNo=n;materialCode=m;batchType=t;quantity=q;productionDate=p;expiryDate=e;createdAt=LocalDateTime.now();}}
/**
 * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
 */
@Entity @Table(name="tr_inspections",uniqueConstraints=@UniqueConstraint(columnNames="inspectionNo")) class BatchInspection{@Id @GeneratedValue(strategy=GenerationType.IDENTITY)Long id;@Column(nullable=false)Long batchId;@Column(nullable=false,length=50)String inspectionNo;@Column(nullable=false,length=20)String result;@Column(nullable=false,length=300)String conclusion;@Column(nullable=false,length=50)String inspector;LocalDateTime inspectedAt;/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  */
protected BatchInspection(){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               */
BatchInspection(Long b,String n,String r,String c,String i){batchId=b;inspectionNo=n;result=r;conclusion=c;inspector=i;inspectedAt=LocalDateTime.now();}}
/**
 * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
 */
@Entity @Table(name="tr_genealogy",uniqueConstraints=@UniqueConstraint(columnNames={"sourceBatchId","targetBatchId"})) class BatchGenealogy{@Id @GeneratedValue(strategy=GenerationType.IDENTITY)Long id;@Column(nullable=false)Long sourceBatchId;@Column(nullable=false)Long targetBatchId;double consumedQuantity;@Column(nullable=false,length=100)String processStep;LocalDateTime createdAt;/**
                                                                                                                                                                                                                                                                                                                                                                                                   * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                   */
protected BatchGenealogy(){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                               * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                               */
BatchGenealogy(Long s,Long t,double q,String p){sourceBatchId=s;targetBatchId=t;consumedQuantity=q;processStep=p;createdAt=LocalDateTime.now();}}
/**
 * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
 */
@Entity @Table(name="tr_events",uniqueConstraints=@UniqueConstraint(columnNames="eventId")) class TraceEvent{@Id @GeneratedValue(strategy=GenerationType.IDENTITY)Long id;@Column(nullable=false,length=60)String eventId;@Column(nullable=false)Long batchId;@Column(nullable=false,length=40)String eventType;@Column(nullable=false,length=120)String location;@Column(nullable=false,length=120)String businessRef;LocalDateTime occurredAt;/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                 * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                 */
protected TraceEvent(){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                         * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                         */
TraceEvent(String e,Long b,String t,String l,String r,LocalDateTime at){eventId=e;batchId=b;eventType=t;location=l;businessRef=r;occurredAt=at;}}
/**
 * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
 */
@Entity @Table(name="tr_recalls",uniqueConstraints=@UniqueConstraint(columnNames="recallNo")) class RecallCase{@Id @GeneratedValue(strategy=GenerationType.IDENTITY)Long id;@Column(nullable=false,length=50)String recallNo;@Column(nullable=false)Long sourceBatchId;@Column(nullable=false,length=20)String level;@Column(nullable=false,length=300)String reason;@Column(nullable=false,length=20)String status="OPEN";int affectedBatchCount;LocalDateTime openedAt;LocalDateTime notifiedAt;/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   */
protected RecallCase(){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           */
RecallCase(String n,Long b,String l,String r,int count){recallNo=n;sourceBatchId=b;level=l;reason=r;affectedBatchCount=count;openedAt=LocalDateTime.now();}}
